apiVersion: v1
kind: Service
metadata:
    name: "recogaks-coturn"
    labels:
        app: "recogaks-coturn"
spec:
    type: LoadBalancer
    ports:
    - port: 3478
      targetPort: 3478
      protocol: TCP
      name: http
    selector:
        app: "recogaks-coturn"